---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "fft-backend-service"
  namespace: "default"
  labels:
    app: "fft-backend"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "fft-backend"
  type: "LoadBalancer"
  loadBalancerIP: ""
